
CREATE TABLE IF NOT EXISTS posts (
    id UUID PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    image_path VARCHAR(255),
    content TEXT NOT NULL,
    text_preview VARCHAR(500) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO POSTS(ID,TITLE,CONTENT,TEXT_PREVIEW)
VALUES
('0a2a4b69-1141-4652-8c6f-ae7fae3ae6e7','test','test test','test'),
('0a2a4b69-2222-4652-8c6f-ae7fae3ae6e7','test2','test2 test2','test2');
